services:
  db:
    image: postgres:18-alpine
    restart: always
    container_name: postgres
    env_file: ./.env
    volumes:
      - db:/var/lib/postgresql
    ports:
      - "5432:5432"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: nodejs
    env_file:
      - ./.env
      - ./server/.env
    ports:
      - "3001:3001"
    depends_on:
      - db
    volumes:
      - ./server:/app
      - server_node_modules:/app/node_modules

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: vite
    environment:
      - VITE_PROXY_TARGET=http://server:3001
    ports:
      - "3002:3002"
    depends_on:
      - server
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules

volumes:
  db:
  server_node_modules:
  client_node_modules:
